import os
import json


def visualization_feature(json_file_path):
    """
    Read a JSON file (e.g., generated by ydata_profiling) and extract:
      1) A list of all feature names.
      2) A list of features where the first key in 'character_counts' is numeric,
         or 'character_counts' is missing.

    Parameters
        json_file_path : str
            Path to the JSON file (e.g., the config JSON generated by ydata_profiling).

    Returns
        tuple of list
            A tuple containing:
            - A list of all feature names.
            - A list of features meeting the specified condition (numeric_key_features).
    """
    if not os.path.exists(json_file_path):
        print(f"파일을 찾을 수 없습니다: {json_file_path}")
        return [], []

    with open(json_file_path, "r", encoding="utf-8") as f:
        eda_data = json.load(f)

    variables = eda_data.get("variables", {})
    all_features = list(variables.keys())
    numeric_key_features = []

    for feature_name, feature_info in variables.items():
        char_counts = feature_info.get("character_counts", {})
        if not char_counts:
            numeric_key_features.append(feature_name)
        else:
            first_key = list(char_counts.keys())[0]
            if first_key.isdigit():
                numeric_key_features.append(feature_name)

    return all_features, numeric_key_features